# apiVersion: v1
# kind: Pod
# metadata:
#   name: busybox
# spec:
#   containers:
#   - name: busybox
#     image: busybox:1.30
#     command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
# --- 
apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels:
    app: nginx
spec:
  containers: 
    - image: nginx:latest
      name: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
