
apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
  namespace: dev
spec:
  containers:
  - name: nginx-containers
    image: nginx:latest
    ports: 
    - name: nginx-port
      protocol: TCP
      containerPort: 8080