name: Environment Variables Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_VARIABLE: "my_value"
      ANOTHER_VARIABLE: "another_value"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print environment variables
        run: |
          echo "MY_VARIABLE: $MY_VARIABLE"
          echo "ANOTHER_VARIABLE: $ANOTHER_VARIABLE"
