name: Clear Branch

on:
  push:
    - ci-test
  workflow_dispatch:
    inputs:
      ref:
        description: "Why trigger?"
        required: true 
        type: string
jobs:
  clear_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Authenticate GitHub CLI
        run: |
          echo "$GITHUB_TOKEN" | gh auth login --with-token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List all branches
        run: |
          git fetch --prune
          for branch in $(git branch -r | grep -v 'HEAD\|main\|master\|ci-test' | sed 's/origin\///'); do
            last_commit_date=$(git log -1 --format=%ci origin/$branch)
            if [[ $(date -d "$last_commit_date" +%s) -lt $(date -d "1 month ago" +%s) ]]; then
              if ! gh pr list --head $branch --repo https://github.com/jiumos/draw/ | grep $branch; then
                echo "Deleting branch: $branch"
                git push origin --delete $branch
              fi
            fi
          done