on:
  push:
    branches: [ master ]

env:
  MAVEN_VERSION: maven:3.8.6-jdk-11
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Env Variable
      run: echo ${{ env.MAVEN_VERSION }}
