name: CI_moleyi

on:
  push:
    branches:
      - main

env:
  CLEAR: 0

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 301
    env:
      CLEAR_VALUE: ${{ CLEAR }}
    if: ${{ env.CLEAR_VALUE == '0' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add more steps for your tests or build process here
