name: CI_moleyi

on:
  push:
    branches:
    - main
jobs:

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 301
    steps:
      - name: init
        run: |
          mkdir test_logs
          export LC_ALL="en_US.utf8"
        shell: bash
      - name: run 
        run: "echo ${LCALL}"
