name: CI_moleyi

on:
  push:
    branches:
    - main
  workflow_dispatch:
    inputs:
      PYTEST_XDIST_WORKER_NUMBER:
        description: 'Worker number'
        required: true
      PYTEST_DF_ENV_NUMBER:
        description: 'deepflow env number'
        required: true
      TEST_CASE:
        description: 'case name or all'
        required: false
        default: 'all'
      DEEPFLOW_SERVER_IMAGE_TAG:
        description: 'server image tag'
        required: false
        default: 'latest'
      DEEPFLOW_AGENT_IMAGE_TAG:
        description: 'agent image tag, default :latest'
        required: false
        default: 'latest'
      NO_REPORT:
        description: 'Report occurred to FeiShu, default 0; no report'
        required: false
      DF_ENVS_FIXED:
        description: 'The test case include server, default 0 '
        required: false
  
        
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 301
    steps:
      - name: init
        env: 
          a: env_test
        run: |
          mkdir test_logs
          export LC_ALL="en_US.utf8"
          echo "LC=${{env.a}}" >> $GITHUB_ENV
        shell: bash
      - name: run 
        run: |
          echo ${LC_ALL}
          echo ${LC}
          echo "test"

          
 
