name: CI_moleyi

on:
  push:
    branches:
    - main
  workflow_dispatch:  # 添加手动触发方式
    inputs:
      parameter_name:
        description: 'Description of the parameter'
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 301
    steps:
      - name: init
        env: 
          a: env_test
        run: |
          mkdir test_logs
          export LC_ALL="en_US.utf8"
          echo "LC=${{env.a}}" >> $GITHUB_ENV
        shell: bash
      - name: run 
        run: |
          echo ${LC_ALL}
          echo ${LC}
          echo "test"
